= Tracing and Observability with Spring Cloud Sleuth + Grafana
Mario Gray <mgray@pivotal.io>
:Author Initials: MVG
:toc:
:icons:
:numbered:
:website: https://cloud.spring.io/spring-cloud-sleuth/

== Motivation
Distrubited application debugging has evolved tremendously over the
past few years. For example, when an application request is made, 
the Managed Diagnostic Context can update the state of current execution
context. This allows for inherent program code tracing without even knowing
the origin or destination of such service. In this article I will overview 
and surface an example of spring-cloud-sleuth - a distributed tracing 
module for spring-cloud.

=== Take a closer look

MDC is the basic building block of scalable tracing. Managed Diagnostic Contexzt
is used to find out when a new thread of context - add thread context too - is 
activated. We use MDC through the SLF4J-mdc moduyle
Break down what MDC does
How does SLF4j affect MDC
how Spring-Cloud-Sleuth Interacts with MDC/slf4j. 
how SCS interacts with any other tracing framework (is possible)
Describe output and destination/configuration of zipkin.  throw in 
dapper,HTrace or other popular tracing too.

=== Observing the cluster
 
How observability affets management, allows us to put performance 
into context.  Describe how to get trace data into Grafana

* Setup the environment using minikube

=== What's in the example
Ideation: Expose GET http://reverse 
                -> microservice (reverse.apply)
                    -> microservice (delay.apply)
          Expose POST http://names
                -> microservice (store.apply)
                    -> microservice (delay.apply)
          Expose GET http://names
                -> microservice (get.apply)
                    -> microservice (delay.apply)

            HTTP 400 - Error state on numbers. 
            HTTP 500 - larger than 80 characters 500's the service

Test Suite ( functional ) 

